name: congdv
markdown: kramdown
kramdown:
    auto_ids:       true
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
    hard_wrap:      false
    input: GFM
    footnote_nr:    1
prose:
    rooturl: '_posts'
    siteurl: 'https://congdv.github.io'
    metadata:
        _posts:
            - name: "title"
              field:
                  label: "Title"
                  element: "text"
                  value: ""
            - name: "date"
              field:
                  label: "date"
                  element: "text"
                  value: "CURRENT_DATETIME"
            - name: "tag"
              field:
                  element: "select"
                  label: "Add Tag"
                  placeholder: "choose Tag"
                  alterable: true
                  options:
                      - name: "Blog"
                        value: "blog"
                      - name: "Notes"
                        value: "notes"
            - name: "layout"
              field:
                  label: "layout"
                  element: "text"
                  value: "article"
            - name: "published"
              field:
                  element: "checkbox"
                  label: "Published"
                  value: false
