name: congdv
markdown: kramdown
prose:
    rooturl: '_posts'
    siteurl: 'https://congdv.github.io'
    metadata:
        _posts:
            - name: "layout"
              field:
                  label: "layout"
                  element: "text"
                  value: "post"
            - name: "date"
              field:
                  label: "date"
                  element: "text"
                  value: "CURRENT_DATETIME"
            - name: "tags"
              field:
                  element: "select"
                  label: "Add Tags"
                  placeholder: "choose Tags"
                  alterable: true
                  options:
                      - name: "Blog"
                        value: "blog"
                      - name: "Notes"
                        value: "notes"
